all: calcFmsy.dll s6model.dll

calcFmsy.dll: calcFmsy.cpp
	Rscript --vanilla -e "TMB::compile('calcFmsy.cpp')"

s6model.dll: s6model.cpp
	Rscript --vanilla -e "TMB::compile('s6model.cpp')"

clean:
	rm -rf *o
