name: Tests

on:
  workflow_run:
    workflows: [Build]
    types:
      - completed

jobs:
  test-s6model:
    runs-on: self-hosted
    steps:
      - name: test s6model
        run: R_LIBS="~/github/s6model/library" make test
  
